### ISSUE TITLE
Part vs. Package convention

### ISSUE THREAD

**Issue by niclashoyer** [carrotIndustries/horizon-pool#102]
I'm about to start my first project in horizon and I need to add some parts. I'm happy to contribute to the pool, but I'm a bit confused by the part/package relation.

Take e.g. the TL074 op amp IC as an example:

Quad Op Amp → TL074 DIP → DIP 14 packages
Quad Op Amp → TL074 TSSOP → TSSOP 14 packages

Is there something like a "combined" or "compatible" part I could define? So if I wanted to create two boards, one SMD and one THT, I'd now have to change the whole schematic.

On the other hand, there are a number of ICs where there are different pins available depending on the package.

So, if designing a schematic I have to choose which package I want to use, maybe that is a good thing :smiley_cat: 

So the correct way is to add a part for each possible package "class"? DOP, SOIC, TSSOP, ... ?

**Comment by atoav** [comment]
Welcome : )

# What is a part?
- the mapping from the pins of one or more units to the pins of a package. If you use more than one unit each of the units can be placed on the schematic seperately.
- a MPN
- a manufacturer name
- some Tags
- a "value" (the name displayed in the schematic)
- a link to the official datasheet (use the one from the manufacturer not from the distributor like mouser etc)
- maybe some parametric data if you add resistors, capacitors and the case

## Inheritence
Each part can inherit one or more values from a _base part._ The goal was to avoid using these base parts in a schematic, but use real available parts that you can buy. So instead of a "TL072" you place "TL072ACP" on your schematic, which is a TL072 DIP8 variant by Texas Instruments, that you can buy under that exact manufacturer part number (MPN).

So each part should be either a **base part** (other parts inherit from it) or an **actual part** you can buy with that very MPN.

## Example
So for example you could have something like this:
```
TL072 (DIP, Base Part)
  |--- TL072ACP
  |--- TL072BCP
  |--- ...
TL072 (SOIC, Base Part)
  |--- TL072CDR
  |--- TL072ACDR
  |--- ...
```

So as it is now you will have to make base parts per package. For very "jelly beans" parts with multiple manufacturers (and therefore datasheets) it can make sense to go even for something like this:
```
Basepart Package A
  |--- Basepart Package A, Manufacturer A
        |--- Actual Part 1
        |--- Actual Part 2
  |--- Basepart Package A, Manufacturer B
        |--- Actual Part 1
        |--- Actual Part 2
```
The idea behind this is, that you can change things in one place and have them fixed in all the inheriting parts.

There is no real need for you to add _all_ parts of a manufacturer. I made the habit to do so "while I am at it", but it means some extra work, and it is entirely your choice.

# JSON
The elements that make up the pool are all json files, so if you can code, you can do very fast generation of parts. I for example scraped the yageo parts from their website and created a few thousand resistor parts in one go.

Replacing a TL072 with a SMD variant. I think rightclick and `Assign Part` might work? Not sure tho..

**Comment by niclashoyer** [comment]
Thank you for the clarification! I thought it would be better if one has a more generic schematic and could derive different board variants from one schematic. As I already stated above this has its own limitations and changing the part in the schematic editor is easy, just clicking "assign part" suffices.

Closing for now, TL072 would actually be the very first part I'd have to add. But I'm just getting used to horizon, so this could take a while.

**Comment by atoav** [comment]
> I thought it would be better if one has a more generic schematic and could derive different board variants from one schematic.

I had similar thoughts at the start, but it didn't turn out to be a problem in practice. Maybe @carrotIndustries already has a plan for this?

Make sure to check the pull requests at:
https://github.com/carrotIndustries/horizon-pool/pulls

You will find, that I already [added a TL072](https://github.com/carrotIndustries/horizon-pool/pull/38) but it didn't get accepted yet, so it is not included in the official pool yet.

Which leads me to another question for @carrotIndustries : do we have a mechanisms for non git-savy users to "preview" pull Requests? That might be needed, if it doesn't exist yet

**Comment by carrotIndustries** [comment]
Having the actual orderable part in the schematic was a deliberate design decision made at very beginning of the project. This greatly simplifies exporting a useful BOM from the schematic that could be shared with contract manufacturers.

Anyhow, for the actual netlist, parts aren't all that important since a 10k 0603 resistor is equivalent to a 1k through hole resistor for netlist purposes. That's why the components in the netlist reference entities rather than parts. Because of that it's possible to change parts referencing the same entity without impact to the netlist.

> I had similar thoughts at the start, but it didn't turn out to be a problem in practice. Maybe @carrotIndustries already has a plan for this?

Variants are something I've had on my mind a few times, but hasn't been important enough to anyone yet.

With variant you'd be able to mark components as "do not place" or replace the part with another one that shares the same package. All of these changes won't affect the board itself, only the BOM and the not yet implemented pick and place export. Thus having this feature before pick&place export seems of little use to me.

> Which leads me to another question for @carrotIndustries : do we have a mechanisms for non git-savy users to "preview" pull Requests? That might be needed, if it doesn't exist yet

https://github.com/carrotIndustries/horizon/issues/231#issuecomment-462092273

I've got a branch gathering dust in which I started working on this, but I still haven't figured out how to handle all the conflicts possible without introducing too much complexity.

**Comment by atoav** [comment]
> I've got a branch gathering dust in which I started working on this, but I still haven't figured out how to handle all the conflicts possible without introducing too much complexity.

How about treating the PRs as "seperate pools" that extend the original pool and can be activated/deactivated like other included pools?

**Comment by niclashoyer** [comment]
@atoav a lot of synth related parts, great :microphone: 

Is there any blocker on these parts? Otherwise I would create my own pool and merge them there, but that is far from ideal. I don't want this to end up just like KiCad where actually everybody build there own part libraries.

**Comment by atoav** [comment]
Every PR I make to the community pool should be more or less okay, I try to resolve blockers quickly, and if there is one with a comment and I didn't do something, well it happens, please add a comment. Most of these are "done" but having a second pair of eyes checking them is reasonable.

If you are interested in synth parts, check out [my fork's work branch](https://github.com/atoav/horizon-pool/tree/work), this is where I merge all my PRs to for private use.
